### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by kanishkarj** [KDani-99/school_timetable#1]
Hello, I had a suggestion. You can try supporting integration with google calender, It'll be really helpful.

**Comment by Outright-Graham** [comment]
I love it. 

Just a suggestion (or maybe I missed this?), is there a way to hyperlink each object in the days? Say to something we have in another place like a details of the lesson?

**Comment by KDani-99** [comment]
Thank you!

We've started developing a new version of this app in Angular (since this code is a bit chaotic), but currently we are working on bigger projects. Once we have the time, we'll finish it.

**Comment by KDani-99** [comment]
New version:
https://github.com/natixco/tabby
Native:
https://github.com/KDani-99/tabby-native
