### ISSUE TITLE
Visualize time per task

### ISSUE THREAD

**Issue by twhitson** [KDani-99/school_timetable#3]
I would love if this app more clearly showed the time taken per task, rather than every task being the same size regardless how much time is allotted. I would imagine it similar to the "week" view in Outlook.

![image](https://user-images.githubusercontent.com/4574457/62709273-a8e2c400-b9ba-11e9-87e1-b8c6af018aa2.png)

**Comment by natixco** [comment]
Hi, thank you for your request. We're just started the development of a new upgraded version of the app. We definitely create a setting for it to make the tasks fix height or dynamic.

**Comment by KDani-99** [comment]
New version:
https://github.com/natixco/tabby
Native:
https://github.com/KDani-99/tabby-native
